### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sukyorsuki** [YuLab-SMU/HDO.db#12]
BiocManager::install("HDO.db")
Warning message:
In install.packages(...) :
  installation of package ‘HDO.db’ had non-zero exit status

Pls help me solve this error, Thx a lot!

**Comment by huerqiang** [comment]
Please provide  more information, and you should use the latest version of R (version 4.22)

**Comment by sukyorsuki** [comment]
I' ve updated the latest version of R. No other information has presented.

**Comment by huerqiang** [comment]
Maybe it is a network problem. If you can provide the screenshot of installation process I may offer more help.

**Comment by sukyorsuki** [comment]
感谢您的回答，我已经更新了Rstudio 和R 但是还是不行，我可以邮件向你请教吗 784038145@qq.com

**Comment by sukyorsuki** [comment]
![image](https://user-images.githubusercontent.com/98321815/202859203-a9333f56-5d26-4e31-87be-78d065d4db5c.png)
![image](https://user-images.githubusercontent.com/98321815/202859241-cade8e49-8bec-46b4-a5e2-13dc5c07fa00.png)

**Comment by huerqiang** [comment]
你的这些warning都是在更新其他包的时候因为网络问题或者权限问题（这种问题windows系统很常见）造成的。重启Rgui之后，你可以只安装HDO.db，在Update all/some/noe 时选择n。

**Comment by sukyorsuki** [comment]
我也试过n 不更新其他包但是也还是一样的warning最后没安装成



---Original---
From: "Erqiang ***@***.***&gt;
Date: Sun, Nov 20, 2022 08:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuLab-SMU/HDO.db] Installation error (Issue #12)




 
你的这些warning都是在更新其他包的时候因为网络问题或者权限问题（这种问题windows系统很常见）造成的。重启Rgui之后，你可以只安装HDO.db，在Update all/some/noe 时选择n。

**Comment by huerqiang** [comment]
那你要看具体是什么warning，warning并不是error，通常不影响你使用这个包。

**Comment by sukyorsuki** [comment]
影响使用 我加载clusterProfiler的时候就加载不上，说我缺HDO.db这个包。我再想想办法谢谢你们这么强大的团队开发的这个包



---Original---
From: "Erqiang ***@***.***&gt;
Date: Sun, Nov 20, 2022 20:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuLab-SMU/HDO.db] Installation error (Issue #12)




 
那你要看具体是什么warning，warning并不是error，通常不影响你使用这个包。
