### ISSUE TITLE
malformed yaml in vignette

### ISSUE THREAD

**Issue by vjcitn** [YuLab-SMU/HDO.db#7]
https://github.com/YuLab-SMU/HDO.db/blob/77b63f4dab8847c5c4487de0cdde63b53f3a9097/vignettes/HDO_vignette.Rmd#L5

this defeats R CMD check.  Please be sure that your package passes R check and BiocCheck.

**Comment by huerqiang** [comment]
@vjcitn Thanks. We have fixed the HDO_vignette.Rmd and HDO.db now passes R check and BiocCheck.
